
[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"

[font]
normal = { family = "DejaVuSansM Nerd Font Mono", style = "Regular" }

[general]
import = [
  "~/.config/alacritty/themes/themes/solarized_dark.toml"
]

[terminal]

