---
- name: Check on nvim directory
  ansible.builtin.stat:
    path: '{{ og_nvim_path }}'
  register: og_nvim_path_stat

- ansible.builtin.assert:
    that:
      - og_nvim_path_stat.stat.islnk is defined
    msg: 'neovim directory not found. Please install neovim.'

- name: Backup original nvim directory
  ansible.builtin.copy:
    src: '{{ og_nvim_path }}'
    dest: '{{ og_nvim_path }}.og'
  when:
    - not og_nvim_path_stat.stat.islnk

- name: Create a symbolic link
  ansible.builtin.file:
    src: '{{ nvim_path }}'
    dest: '{{ og_nvim_path }}'
    state: link
