---
- name: Check on .byobu directory
  ansible.builtin.stat:
    path: '{{ og_byobu_path }}'
  register: og_byobu_path_stat

- ansible.builtin.assert:
    that:
      - og_byobu_path_stat.stat.islnk is defined
    msg: '{{ og_byobu_path }} does not exist. Make sure Byobu is installed!'

- name: Backup original byobu directory
  ansible.builtin.copy:
    src: '{{ og_byobu_path }}'
    dest: '{{ og_byobu_path }}.og'
  when:
    - not og_byobu_path_stat.stat.islnk

- name: Create a symbolic link
  ansible.builtin.file:
    src: '{{ byobu_path }}'
    dest: '{{ og_byobu_path }}'
    state: link
