- name: Configure and/or update CLI environment
  hosts: localhost
  connection: local

  vars:
    base_dir: '{{ playbook_dir | dirname }}'
    gitignore_path: '{{ base_dir }}/git/gitignore'
    git_aliases_path: '{{ base_dir }}/aliases/git'

  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present
      vars:
        packages: "{{ lookup('file', base_dir ~ '/manjaro_packages').splitlines() }}"
      become: true
      tags: packages

    - name: Change shell to zsh
      become: yes
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh

    - name: Install dotfiles
      ansible.builtin.shell: ~/.dotfiles/install
      register: dotbot_output
      changed_when: '"Creating" in dotbot_output.stdout'

    - name: Git configuration
      block:

      - name: Configure global .gitignore file
        community.general.git_config:
          name: core.excludesfile
          scope: global
          value: '{{ gitignore_path }}'

      - name: Include git aliases file
        community.general.git_config:
          name: include.path
          scope: global
          value: '{{ git_aliases_path }}'

      - name: Make default branch "main"
        community.general.git_config:
          name: init.defaultBranch
          scope: global
          value: main

      - name: Automatically set up remote tracking branch when pushing
        community.general.git_config:
          name: push.autoSetupRemote
          scope: global
          value: true
