# XDG dirs
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"

# Zsh config directory
ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# Dotfiles directory
DOTFILES_DIR="$HOME/.dotfiles"

# Add .local/bin to PATH
export PATH="$HOME/.local/bin:$PATH"

# Neovim
export EDITOR="nvim"
export VISUAL="nvim"
export DIFFPROG='nvim -d'

# Ripgrep
export RIPGREP_CONFIG_PATH="$DOTFILES_DIR/ripgreprc"

# Bat theme
export BAT_THEME='Solarized (dark)'

# FZF
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Docker Rootless
export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock

# Ruby gems
if [[ -x $(command -v ruby) ]]; then
  export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
  export PATH="$PATH:$GEM_HOME/bin"
fi
